apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: NodePort
  selector:
    app: helloworld-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
