apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld-api
  template:
    metadata:
      labels:
        app: helloworld-api
    spec:
      containers:
      - name: helloworld-api
        image: helloworld-api:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"  # Minimum memory the container is guaranteed
            cpu: "250m"      # Minimum CPU the container is guaranteed
          limits:
            memory: "256Mi"  # Maximum memory the container can use
            cpu: "500m"      # Maximum CPU the container can use
